/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 latte_parquet_01_01_draco.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LatteParquet0101(props) {
  const { nodes, materials } = useGLTF(
    '/gltf/appartement_haussmannien/sol/lattes/latte_parquet_01_01_draco.gltf',
  )
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.latte_parquet_01_01.geometry}
        material={materials['Material.008']}
        position={[-14.6, -0.1, 0]}
      />
    </group>
  )
}

useGLTF.preload('/latte_parquet_01_01_draco.gltf')
