import * as THREE from 'three'

export const materialProps = {
  alphaTest: 0,
  alphaToCoverage: false,
  blendAlpha: 0,
  blendColor: new THREE.Color(0x000000),
  blendDst: THREE.OneMinusSrcAlphaFactor,
  blendEquation: THREE.AddEquation,
  blending: THREE.NormalBlending,
  blendSrc: THREE.SrcAlphaFactor,
  clipIntersection: false,
  clipShadows: false,
  colorWrite: true,
  depthFunc: THREE.LessEqualDepth,
  depthTest: true,
  depthWrite: true,
  forceSinglePass: false,
  stencilWrite: false,
  stencilWriteMask: 0xff,
  stencilFunc: THREE.AlwaysStencilFunc,
  stencilRef: 0,
  stencilFuncMask: 0xff,
  stencilFail: THREE.KeepStencilOp,
  stencilZFail: THREE.KeepStencilOp,
  stencilZPass: THREE.KeepStencilOp,
  name: '',
  opacity: 1,
  polygonOffset: false,
  polygonOffsetFactor: 0,
  polygonOffsetUnits: 0,
  premultipliedAlpha: false,
  dithering: false,
  side: THREE.DoubleSide,
  toneMapped: true,
  transparent: false,
  version: 0,
  vertexColors: false,
  visible: true,
  userData: {},
}

export const meshStandardMaterialProps = {
  aoMapIntensity: 1,
  bumpScale: 1,
  color: new THREE.Color(0xffffff),
  displacementScale: 1,
  displacementBias: 0,
  emissive: new THREE.Color(0x000000),
  emissiveIntensity: 1,
  envMapIntensity: 0,
  flatShading: false,
  fog: true,
  lightMapIntensity: 1,
  metalness: 0,
  normalMapType: THREE.TangentSpaceNormalMap,
  normalScale: new THREE.Vector2(1, 1),
  roughness: 1,
  wireframe: false,
  wireframeLinecap: 'round',
  wireframeLinejoin: 'round',
  wireframeLinewidth: 1,
}

export const meshPhysicalMaterialProps = {
  attenuationColor: new THREE.Color(0xffffff),
  attenuationDistance: Infinity,
  clearcoat: 0,
  clearcoatNormalScale: new THREE.Vector2(1, 1),
  clearcoatRoughness: 0,
  ior: 1.5,
  reflectivity: 0.5,
  iridescence: 0,
  iridescenceIOR: 1.3,
  /* iridescenceThicknessRange: [100, 400], */
  sheen: 0,
  sheenRoughness: 1,
  sheenColor: new THREE.Color(0x000000),
  specularIntensity: 1,
  specularColor: new THREE.Color(0xffffff),
  thickness: 0,
  transmission: 0,
}
